version: "3"
services:
  app:
    build:
      context: .
    tty: true
    volumes:
      - .:/go/src
    ports:
      - 8080:8080
    environment:
      GOPATH: /go
    depends_on:
      - db
  db:
    image: mysql:latest
    ports:
      - 3306:3306
    volumes:
      - db-volume:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
volumes:
  db-volume:
